# Generated by Django 3.0.8 on 2020-08-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_auto_20200819_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Author',
            field=models.CharField(default='', max_length=15),
        ),
    ]
