# Generated by Django 3.0.8 on 2020-08-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_contact_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
