# Generated by Django 3.0.8 on 2020-09-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20200820_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Blog_picture',
            field=models.ImageField(blank=True, default='code.jpeg', null=True, upload_to=''),
        ),
    ]
