# Generated by Django 3.0.8 on 2020-09-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_blog_blog_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_picture',
            field=models.ImageField(blank=True, default='pic.jpg', null=True, upload_to=''),
        ),
    ]
