# Generated by Django 3.0.8 on 2020-09-26 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20200923_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_picture',
            field=models.ImageField(blank=True, default='code.jpg', null=True, upload_to='Uploaded/images'),
        ),
    ]
